apiVersion : apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deploy
  labels:
    app : {{ .Release.Name }}-deploy
spec:
  replicas : {{ .Values.replicaCount }}
  selector:
    matchLabels:
      project: {{ .Release.Name }}
  strategy:
    type: RollingUpdate  
    rollingUpdate:
      maxSurge: 1         
      maxUnavailable: 0   
                    
  template:
    metadata:
      labels: 
        project: {{ .Release.Name }}
    spec:
      containers:
        - name : {{ .Release.Name }}-web
          image: {{ .Values.image }}
          ports:
            - containerPort: 80    